# Generated by Django 4.1.7 on 2023-06-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('ename', models.CharField(max_length=100)),
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('eage', models.IntegerField()),
            ],
        ),
    ]
